name = "Vanilla Bootstrap"
license = "MIT"
licenselink = "https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme/blob/master/LICENSE"
description = "A vanilla Bootstrap theme for Hugo"
homepage = "https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme"
tags = ["todo"]
features = ["todo"]
min_version = "0.48"

[author]
  name = "Zachary Betz"
  homepage = "https://zwbetz.com/"
