baseURL = "https://example.com"
languageCode = "en-us"
title = "Vanilla"
# Uncomment below to enable theme
# theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-123456789-1"

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[menu]
  [[menu.main]]
    name = """<i data-feather="home"></i> Home"""
    url = "/"
    weight = 1
  [[menu.main]]
    name = """<i data-feather="edit"></i> Blog"""
    url = "/post/"
    weight = 2
  [[menu.main]]
    name = """<i data-feather="tag"></i> Tags"""
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = """<i data-feather="smile"></i> About"""
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = """<i data-feather="rss"></i> RSS"""
    url = "/index.xml"
    weight = 5

[params]
  includeBootstrapJs = false
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Welcome to the Vanilla theme demo. Have a look around. Maybe even eat some ice cream."
  footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)."