baseURL = "https://example.com"
languageCode = "en-us"
title = "Vanilla"
# Uncomment below to enable theme
# theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-123456789-1"

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/ for other icons
[menu]
  [[menu.main]]
    name = "Home"
    pre = """<i data-feather="home"></i>"""
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = """<i data-feather="edit"></i>"""
    url = "/post/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = """<i data-feather="tag"></i>"""
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    pre = """<i data-feather="smile"></i>"""
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "RSS"
    pre = """<i data-feather="rss"></i>"""
    url = "/index.xml"
    weight = 5

[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Welcome to the Vanilla theme demo. Have a look around. Maybe even eat some ice cream."
  footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"